FROM python:3.11-slim

WORKDIR /app
ENV PYTHONPATH=/app

COPY agora_requirements.txt .
RUN pip install --no-cache-dir -r agora_requirements.txt

# Copy entire source code
COPY . .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

